include:
  # - board: nice_nano_v2
  #   shield: bwwjj40_left
  # - board: nice_nano_v2
  #   shield: bwwjj40_right
  # - board: nice_nano_v2
  #   shield: bwwjj20_L
  - board: nice_nano_v2
    shield: bwwjj20_R
  # - board: nice_nano_v2
  #   shield: settings_reset