include:
  - board: nice_nano_v2
    shield: bwwjjkeyboard_left
  - board: nice_nano_v2
    shield: bwwjjkeyboard40_right
  - board: nice_nano_v2
    shield: bwwjjkeyboard20_L
  - board: nice_nano_v2
    shield: bwwjjkeyboard20_R
  - board: nice_nano_v2
    shield: settings_reset